spring:
  application:
    name: Academy Members MCP Server
  ai:
    mcp:
      server:
        name: academy-members-mcp-server
        version: 1.0.0
        protocol: streamable
        type: sync
